apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-content-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeName: static-content-pv



